### ISSUE TITLE
The Plugin loads on Paper 1.20.1 but nothing happens

### ISSUE THREAD

**Issue by Larres** [Foxikle/CustomNPCs#10]
I can load the Plugin on my Paper 1.20.1 Server with no problems [CNPC] Enabling CustomNPCs v1.3
but after typing as an admin:
/customnpcs:npc create test 
or
/customnpcs:npc help 
nothing happens

**Comment by Foxikle** [comment]
Try typing `/npc create`

**Comment by Foxikle** [comment]
This issue was fixed in #11 
Thanks for reporting it!
