### ISSUE TITLE
Latest update - NPCS.yml update error. 

### ISSUE THREAD

**Issue by dev-nolant** [Foxikle/CustomNPCs#101]
**Describe the bug**
When you uploaded the updated today, it noticed my config file was outdated, and suggested I updated. I updated, and it didn't update any of my yml configs, so I just deleted the CustomNPCs folder and allowed it to create fresh. After doing so, it worked for one launch, where I was able to create NPCs. After a restart, the config file was fine, but the npcs.yml was reverted to 1.6 which caused the plugin to disable itself. 

I fixed this by manually going into npcs.yml and setting the version to 1.7 at the top. Upon restart it changed this version to 1.8, and worked.

**To Reproduce**
1. Download the newest update to the plugins folder.
2. Attempt to run the plugin.
3. If fail, delete CustomNPCs folder.

**Expected behavior**
I expected the npcs.yml to update accordingly after introducing the new plugin jar.

**Screenshots**
N/A

**Server(please complete the following information):**
 - Server Software: Paper/Velocity
 - Other Plugins: pAPI and non-conflicting
 - Version : 1.8 according to the npcs.yml

**Additional context**
N/A

**Comment by Foxikle** [comment]
It is interesting that the migration failed. Was there an error in the console after the first time running the newest version? I see the issue with changing the file now. I am going to publish a hotfix in a moment.

**Comment by Foxikle** [comment]
> Version : 1.8 according to the npcs.yml

This version is independent from the the plugin version. I really should replace it with an integer value. You can view the plugin version by typing /npc (Which doesn't help if it cannot be enabled :|)

Regardless, the newest release fix it
