### ISSUE TITLE
Renaming world's folder removes all NPCs for that world

### ISSUE THREAD

**Issue by TristinCodingham** [Foxikle/CustomNPCs#102]
**Describe the bug**
Renaming world's folder removes all NPCs for that world completely out of existence yet their configuration still remains inside npcs.yml. Also going into the npcs.yml file and changing each NPC's `world` to match the updated world's name does nothing (Rightfully so since editing the npcs.yml manually is discouraged).

**To Reproduce**
1. Go to a world and `/npc create`
2. Once the NPC is created in-game, shut down the server
3. Navigate to that world folder in the server files and rename it to something else
4. Restart the server
5. Go to the renamed world in-game and notice the NPC is gone
6. Try using `/npc goto` and notice the auto complete also does not know of it's existence
7. Go to the server files/plugins/CustomNPCs/npcs.yml and notice they still exist there with their `world` set to the old world's name

**Expected behavior**
Have a command such as `/npc clone world <old_world_name> <new_world_name>` that can be used after renaming a world that contained NPCs, they should automatically update their `world` property and be ported to the new world without changing any of their other properties.

**Screenshots**
Wouldn't really help in this scenario

**Server(please complete the following information):**
 - Server Software: Purpur
 - Other Plugins: 
   - Paper Plugins: (1):
     - CrazyCrates
   -  Bukkit Plugins: (23):
     - BetterGUI, BetterRTP, ClearLag, CrazyEnchantments, CustomNPCs, DecentHolograms, DiscordSRV, Essentials, Esse
ntialsChat, EssentialsSpawn, floodgate, Geyser-Spigot, KeepDeathDrop, LuckPerms, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, MyCommand, PlaceholderAPI, TAB, Vault, WorldEdit, WorldGuard
 - Version [e.g. 1.21.1]

**Additional context**

**Comment by Foxikle** [comment]
Changing the world would indeed result in issues like this. I agree that cloning should support multiple worlds. The npcs should remain in the npcs.yml file, even if the world is invalid. It will print a nasty message to the config, but that ist mostly for show, and the plugin still works fine. The one problem with the `/npc clone world <old_world> <new_world>` is the validation. Additionally, where would the npc be positioned? Your current location, but in the new world? Or what about the npc's location in the new world. As you can probably see, there is a lot of ambiguity. 

You can use the `/npc clone` command on to clone an NPC from an already existing world, but as I just tested it, it is a little janky, and doesn't quite work as intended. 

Additionally, it seems like you might be looking for a command to fix broken configs, which seems like a useful feature. It might work like `/npc fixconfig`. In which it would prompt the user to select which world to set the NPCs to.

**Comment by TristinCodingham** [comment]
Yeah I agree, there is a lot of ambiguity. I was in the mindset of knowing that in my situation both worlds are identical so cloning the world over should just use whatever positioning system the npcs currently use, but I see now this isn't a long term solution or even a good one.

In the event that I request a feature such as `/npc fixconfig`, would this also need to follow the assumption that the world the user will input would need to be identical to the world the NPC was already in? otherwise the positioning ambiguity still remains.

**Comment by Foxikle** [comment]
I think that the `/npc fixconfig` would not change anything unless the user specifies a conversion "factor". Ie, an extra argument like ENSURE_SAFE, meaning the npc wouldn't be floating or in the ground. But by default it would keep the npc's position the same.
