### ISSUE TITLE
Ability to fix potential config issues `/npc fixconfig` 

### ISSUE THREAD

**Issue by TristinCodingham** [Foxikle/CustomNPCs#104]
**Is your feature request related to a problem? Please describe.**
This feature request is based on [this issue](https://github.com/Foxikle/CustomNPCs/issues/102)

**Describe the solution you'd like**
Relating to the issue opened above, in this instance it would prompt the user what they would like to be fixed, the current option would be 'world' in order to update the npcs.yml `world` property. Eg. `/npc fixconfig world`

**Describe alternatives you've considered**
It doesn't make sense to update/fix all the npcs `world` property (not sure if this would be the case), perhaps something similar to `/npc edit <npc_name>` but unfortunately a byproduct of the issue described above is all the npcs affected also disappear from any tab autocomplete functionality. I haven't tested to `/npc edit <npc_I_know_exists_in_config_but_does_not_autocomplete>` 

**Additional context**
This feature can be used for potential future config issues too

**Comment by Foxikle** [comment]
I agree with this approach! You can look forward to seeing something like this in pre-release 10!

Thank you for making a suggestion :)
