### ISSUE TITLE
Keep chunks loaded in radius

### ISSUE THREAD

**Issue by TUBEOF** [Foxikle/CustomNPCs#42]
I wish it would be possible to set a flag for NPCs, so Chunks will not be unloaded and the NPCs can be used as Chunk Loaders, for example for Spawners. Right now, there is still an other plugin needed like KeepChunks, but it would be nice, when it's directly integrated.

I would also love to see, when its possible to set a range ot chunks, for example: 6x6 chunks around the chunk of the NPC.

**Comment by Foxikle** [comment]
That’s an interesting idea! Unfortunately I have exams next week so I probably won’t have time to implement this in a timely manner.
