### ISSUE TITLE
Excellent plugin but very flawed

### ISSUE THREAD

**Issue by lucasesvlins** [Foxikle/CustomNPCs#91]
I have a paper server in version 1.20.1, I was looking for an npc plugin, then I found CustomNPCs. a very user friendly and easy to configure plugin! but I need to report some failures I had with the plugin, not with the intention of harming, more warning about bugs so creators can improve. I'm having two problemsm, First, when I create a new NPC, in addition to the NPC name that I put myself, a large text still appears, full of numbers and letters, that I don't know what it is! the second problem I'm having, I can't color the text on my NPC's hologram! So that's it, I wanted to be able to have an updated version, or if I'm doing something wrong, I wanted to help so I can fix it. Sorry for my bad English, I'm Brazilian and I'm using Google Translate.
![bug](https://github.com/user-attachments/assets/a0e5f7e7-d506-408e-85ce-ea4f5232adc6)

**Comment by Foxikle** [comment]
Thank you for reaching out. I am aware of the issues with portions of the NPC's uuid being visible to the players. I simply  do not have the time to sit down and tie up all of the loose ends right now. Can you please send me the raw npc name so I can diagnose the issues with colors?

Cheers,
Foxikle

**Comment by NALucaas** [comment]
# here is my npcs.yml

Do not edit this file. Foxikle is not responsible for any data loss.
version: 1.6
95ec52dd-fa77-4ff4-a26b-7eb6dfb6344e:
  value: ewogICJ0aW1lc3RhbXAiIDogMTY2NjMwMDA0NTk3MCwKICAicHJvZmlsZUlkIiA6ICIwODFiZTAxZmZlMmU0ODMyODI3MDIwMjBlNmI1M2ExNyIsCiAgInByb2ZpbGVOYW1lIiA6ICJMeXJpY1BsYXRlMjUyNDIiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmMxNjBmYmQxNmFkYmM0YmZmMjQwOWU3MDE4MGQ5MTEwMDJhZWJjZmE4MTFlYjZlYzNkMTA0MDc2MWFlYTZkZCIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9CiAgfQp9
  signature: dZyB5xHwSpFdAWa97CPszBpcCVftab6nlaGG7CUkL9RSm+I4nrWOqka8cRWPq0ocpv7uMm4/l5MonsSI7CeInuT6SiJrFI2rlLVelHNmrwkC7VklvFIFfB5LGYpRU4ChRpOfdVilFBRVYt1lUB3bADZZ+UdIZnAwD1PV6muk1hbj/PCFUCBwBn4CAmSXDxi3D0zxVbY1/Bqekc+c9+jOGZ756dukyciQhpmGL8oSfNFLpC3Hthq4g6izaU2J515OYg8079T9UlC13XywaFJWTWe3lRrfwNfq4YNvyBY9bVcihrGX2YGPKpw6MdT42zn1k9E1PoP4fl5o6leesDXRps5CQV28qixzdpJbHQbvK1AtvbCQCSj8l3nBO9J006pul/FmST2Bx9dLCrpvQSOynMFHHplLm+Nlbsa0vAX+eldLpD4Vv39obpZ16WcgkulIJ72ivOjw3HCdn9pIynXupL8KSLzPkBYfqr+esoIkmB84Fc6F0isOnnrHamCqcDYhCpFdyd8gPgFGyI5E9vUw84d9gSHJtLHbxk0IowHbRs0zrTbAwO6sGX2/q91cUjFSvzOEmSsvGbl6x91G7ATirHLZcRgw6Ubyv7CleJbX0UpSAmP+nXNuZvslNRPo4/CNgOTl0LEQkfVeYEBd4Qz3F5+VKSe8MI2FtGB3QI1dV/c=
  skin: A skin imported via a URL
  clickable: true
  customHologram: '%bungee_swduelsone%'
  hideInteractableHologram: false
  location:
    ==: org.bukkit.Location
    world: swlobbyone
    x: 0.49609426392218625
    y: 73.0
    z: -57.42859296916705
    pitch: 3.1519046
    yaw: -0.26333618
  actions:
  - '{"actionType":"SEND_TO_SERVER","args":["swduelsone"],"delay":1,"mode":"ONE","conditionals":[]}'
  handItem:
    ==: org.bukkit.inventory.ItemStack
    v: 3465
    type: NETHERITE_SWORD
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: '{"italic":false,"color":"green","text":"NETHERITE_SWORD"}'
      lore:
      - '{"italic":false,"color":"yellow","text":"Click this slot with"}'
      - '{"italic":false,"color":"yellow","text":"an item to change."}'
      - '{"italic":false,"color":"red","text":"Rick click to remove"}'
      ItemFlags:
      - HIDE_ATTRIBUTES
      - HIDE_DYE
      PublicBukkitValues:
        customnpcs:woody-menu: 5ca559fc-521a-4b18-a725-058852e7ab8c
  offhandItem:
    ==: org.bukkit.inventory.ItemStack
    v: 3465
    type: SHIELD
    meta:
      ==: ItemMeta
      meta-type: TILE_ENTITY
      display-name: '{"italic":false,"color":"green","text":"SHIELD"}'
      lore:
      - '{"italic":false,"color":"yellow","text":"Click this slot with"}'
      - '{"italic":false,"color":"yellow","text":"an item to change."}'
      - '{"italic":false,"color":"red","text":"Rick click to remove"}'
      ItemFlags:
      - HIDE_ATTRIBUTES
      - HIDE_DYE
      PublicBukkitValues:
        customnpcs:woody-menu: 7a2394f5-069e-4a51-b002-3367216aced5
      blockMaterial: SHIELD
  headItem:
    ==: org.bukkit.inventory.ItemStack
    v: 3465
    type: DIAMOND_HELMET
    meta:
      ==: ItemMeta
      meta-type: ARMOR
      display-name: '{"italic":false,"color":"green","text":"DIAMOND_HELMET"}'
      lore:
      - '{"italic":false,"color":"yellow","text":"Click this slot with"}'
      - '{"italic":false,"color":"yellow","text":"a helmet to change."}'
      - '{"italic":false,"color":"red","text":"Rick click to remove"}'
      ItemFlags:
      - HIDE_ATTRIBUTES
      - HIDE_DYE
      PublicBukkitValues:
        customnpcs:woody-menu: 166ed8ee-b025-4a92-9230-021ef356ac3c
  chestItem:
    ==: org.bukkit.inventory.ItemStack
    v: 3465
    type: DIAMOND_CHESTPLATE
    meta:
      ==: ItemMeta
      meta-type: ARMOR
      display-name: '{"italic":false,"color":"green","text":"DIAMOND_CHESTPLATE"}'
      lore:
      - '{"italic":false,"color":"yellow","text":"Click this slot with"}'
      - '{"italic":false,"color":"yellow","text":"a chestplate to change."}'
      - '{"italic":false,"color":"red","text":"Rick click to remove"}'
      ItemFlags:
      - HIDE_ATTRIBUTES
      - HIDE_DYE
      PublicBukkitValues:
        customnpcs:woody-menu: 48c83aa3-b467-4a3e-88ec-9c92d9722ad0
  legsItem:
    ==: org.bukkit.inventory.ItemStack
    v: 3465
    type: DIAMOND_LEGGINGS
    meta:
      ==: ItemMeta
      meta-type: ARMOR
      display-name: '{"italic":false,"color":"green","text":"DIAMOND_LEGGINGS"}'
      lore:
      - '{"italic":false,"color":"yellow","text":"Click this slot with"}'
      - '{"italic":false,"color":"yellow","text":"a pair of leggings"}'
      - '{"italic":false,"color":"yellow","text":"to change."}'
      - '{"italic":false,"color":"red","text":"Rick click to remove"}'
      ItemFlags:
      - HIDE_ATTRIBUTES
      - HIDE_DYE
      PublicBukkitValues:
        customnpcs:woody-menu: 4d988dac-5afa-4668-a252-4d14462fb9f7
  feetItem:
    ==: org.bukkit.inventory.ItemStack
    v: 3465
    type: DIAMOND_BOOTS
    meta:
      ==: ItemMeta
      meta-type: ARMOR
      display-name: '{"italic":false,"color":"green","text":"DIAMOND_BOOTS"}'
      lore:
      - '{"italic":false,"color":"yellow","text":"Click this slot with"}'
      - '{"italic":false,"color":"yellow","text":"a pair of boots to "}'
      - '{"italic":false,"color":"yellow","text":"change."}'
      - '{"italic":false,"color":"red","text":"Rick click to remove"}'
      ItemFlags:
      - HIDE_ATTRIBUTES
      - HIDE_DYE
      PublicBukkitValues:
        customnpcs:woody-menu: 50f8249c-6273-4943-8606-bc68d7668484
  name: Duels
  world: swlobbyone
  direction: -90.0
  tunnelvision: true
# DO NOT, under ANY circumstances modify the 'version' field. Doing so can cause catastrophic data loss.

**Comment by Foxikle** [comment]
You didn't add any color codes to it. It uses MiniMessage formatting. For example if you wanted the text to be gold you would use `<gold>Duels`. Please note, if google translate translated the word "gold", please make sure it is gold in english, as that is what minimessage uses.

**Comment by NALucaas** [comment]
I see, I didn't know that, thank you very much for explaining. So I would use <red>Duels ? One more question I have, I wanted to do, <yellow> Click to play <red>Duels <yellow>%bungee_swduelsone%, Will it work? Will it be underneath each other?

**Comment by Foxikle** [comment]
Since it only spawns two displays, you should put the click to play in the name input. But to make it a new line, put a <newline> between <red>Duels and the <yellow>Click to play

**Comment by NALucaas** [comment]
It worked, now there's just this code behind it which is a bug. 
![pegou](https://github.com/user-attachments/assets/9aecf772-f095-41b0-a638-62338b0b47f3)

**Comment by Foxikle** [comment]
Yep! I am aware of that bug and cannot fix it immediately. I'll fix it as soon as i get the chance. Sorry for the inconvenience :(

**Comment by NALucaas** [comment]
Thank you, this plugin you created is very good! an excellent plugin! So don't take too long to fix these little flaws, please. I will be making a donation this week to help improve the plugin.

**Comment by Foxikle** [comment]
hey! I'm just letting you know that I am working on the update this weekend. With any luck it will be done on sunday.

Cheers,
Foxikle

**Comment by Foxikle** [comment]
Hey I fixed the issue in this release!
https://github.com/Foxikle/CustomNPCs/releases/tag/v1.7-pre3
