### ISSUE TITLE
Remove NPC name Text background

### ISSUE THREAD

**Issue by FelixBrs** [Foxikle/CustomNPCs#97]
**Is your feature request related to a problem? Please describe.**
Since the name is already a textdisplay maybe use more of its provided features such as removing or coloring the text background

**Describe the solution you'd like**
npc.getSettings().hideTextBackground(true/false) or
npc.getSettings().setTextBackgroundColor(#xxxxxx)

Also could add more of the text display features like size , text shadow , visibility through walls ....

**Comment by Foxikle** [comment]
This is quite feasible, but it would probably only get support through the API for the foreseeable future.
